NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('news.urls')),
    path("accounts/", include("allauth.urls")),
]

accounts/urls.py
from django.urls import path
from .views import SignUp

urlpatterns = [
    path('signup', SignUp.as_view(), name='signup'),
]

news/urls.py
from django.urls import path
from .views import PostsList, PostDetail, PostsSearch, PostCreate, PostEdit, PostDelete


urlpatterns = [
   path('', PostsList.as_view(), name='post_list'),
   path('<int:pk>', PostDetail.as_view(), name='post_detail'),
   path('search', PostsSearch.as_view(), name='post_search'),
   path('create/', PostCreate.as_view(), name='post_create'),
   path('<int:pk>/edit/', PostEdit.as_view(), name='post_edit'),
   path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
]

accounts/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    def __str__(self):
        return f'{self.authorUser}'

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.ratingAuthor = pRat * 3 + cRat
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = (
        (NEWS, 'новость'),
        (ARTICLE, 'статья'),
    )
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

    def preview(self):
        return self.text[0:123] + '...'

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f' {self.postThrough} - категория {self.categoryThrough}'


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def __str__(self):
        return f'Комментарий {self.pk}'

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="Email")
    first_name = forms.CharField(label="Имя")
    last_name = forms.CharField(label="Фамилия")

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        )

news/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'author',
            'categoryType',
            'postCategory',
            'title',
            'text',
        ]

accounts/views.py
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView
from .forms import SignUpForm


class SignUp(CreateView):
    model = User
    form_class = SignUpForm
    success_url = '/accounts/login'

    template_name = 'registration/signup.html'

news/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from .models import Post
from .filters import PostFilter
from .forms import PostForm


class PostsList(ListView):
    model = Post
    ordering = "author"
    template_name = "posts.html"
    context_object_name = "posts"
    paginate_by = 3


class PostDetail(DetailView):
    model = Post
    template_name = 'post.html'
    context_object_name = 'post'


class PostsSearch(ListView):
    model = Post
    ordering = "author"
    template_name = "posts_search.html"
    context_object_name = "posts"

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


class PostCreate(PermissionRequiredMixin, CreateView):
    permission_required = ('news.add_post',)
    form_class = PostForm
    model = Post
    template_name = 'post_edit.html'


class PostEdit(PermissionRequiredMixin, UpdateView):
    permission_required = ('news.change_post',)
    form_class = PostForm
    model = Post
    template_name = 'post_edit.html'


class PostDelete(DeleteView):
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('post_list')

templates/post.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% block title %}
Post
{% endblock title %}

{% block content %}
<p><h1>{{ post.title|censor }}</h1></p>
<p>{{ post.text|censor }}</p>
<p>{{ post.dateCreation|date:'d M Y' }}</p>

{% endblock content %}

templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление новости</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ post.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Создать/отредактировать пост</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

templates/posts.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Posts
{% endblock title %}

{% block content %}
    <h1>Наши новости</h1>
    <h3>Всего новостей: {{ posts|length }}</h3>
    <hr>

    {% if perms.news.add_post %}
    <a href="{% url 'post_search' %}">Найти</a>
    <a href="{% url 'post_create' %}">Создать пост</a>
    {% endif %}
    <table>
        <tr>
           <td>Заголовок</td>
           <td>Категория</td>
           <td>Дата публикации</td>
           <td>Текст статьи</td>

            {% if perms.news.change_post or perms.news.delete_post %}
            <td>Действия</td>
            {% endif %}
        </tr>
        {% for post in posts|dictsortreversed:'dateCreation' %}
        <tr>
           <td><a href="{% url 'post_detail' pk=post.id %}">{{ post.title|censor }}</a></td>
           <td>{{ post.categoryType }}</td>
           <td>{{ post.dateCreation|date:'d M Y' }}</td>
           <td>{{ post.text|truncatechars:20|censor }}</td>
           <td>
               {% if perms.news.change_post %}
               <a href="{% url 'post_edit' pk=post.id %}">Изменить</a>
               <a href="{% url 'post_delete' pk=post.id %}">Удалить</a>
               {% endif %}
           </td>
        </tr>
        {% endfor %}
    </table>
    {% if page_obj.has_previous %}
        <a href="?page=1">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}

templates/posts_search.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Posts
{% endblock title %}

{% block content %}
    <h1>Наши новости</h1>
    <h3>Всего новостей: {{ posts|length }}</h3>
    <form action="" method="get">
        {{ filterset.form.as_p }}
        <input type="submit" value="Найти" />
    </form>
    <hr>
    <table>
        <tr>
           <td>Заголовок</td>
           <td>Категория</td>
           <td>Дата публикации</td>
           <td>Текст статьи</td>
        </tr>
        {% for post in posts|dictsortreversed:'dateCreation' %}
        <tr>
           <td>{{ post.title|censor }}</td>
           <td>{{ post.categoryType }}</td>
           <td>{{ post.dateCreation|date:'d M Y' }}</td>
           <td>{{ post.text|truncatechars:20|censor }}</td>
        </tr>
        {% endfor %}
    </table>

{% endblock content %}